### ISSUE TITLE
Import .inp : Demands without pattern

### ISSUE THREAD

**Issue by hyperprogram2** [neslerel/QGISRed#76]
Hello,

When importing an INP file from Epanet into Qgisred, some jointures have a demand value but no associated demand pattern.
For junctions with several demand catgeroies in Epanet, some demands patterns are also missing.

for example in the attached files :
In Epanet INP :   Junction J146783 has '067' as demand Pattern
![image](https://user-images.githubusercontent.com/92710394/142639086-adfad826-bf73-4cee-8b04-431c7355d8d8.png)

but after importing in QgisRed, the demand pattern disapeared for J146783 whereas the Demand Pattern exist in Qgisred
![image](https://user-images.githubusercontent.com/92710394/142639625-eb902417-b4e4-4979-8108-906f6801cd56.png)
![image](https://user-images.githubusercontent.com/92710394/142640416-d95e939b-5771-471c-bd01-7c50525704b1.png)

For Jointure J153255 :  2 Demand Pattern in Epanet but 0 associated in Qgisred
   In Epanet :
![image](https://user-images.githubusercontent.com/92710394/142640822-bda6de82-98be-479e-a41f-c0b917b9a109.png)
  In QGisred :
![image](https://user-images.githubusercontent.com/92710394/142640667-0e9074a6-8eb6-4008-b7e3-6ed7a0257c54.png) 
![image](https://user-images.githubusercontent.com/92710394/142641454-d259550e-c121-4a11-a6e6-8872a4363ccc.png)

Example file :
[TEST_export_demands.zip](https://github.com/neslerel/QGISRed/files/7570966/TEST_export_demands.zip)

I use Qgis 3.16.1 and Qgisred 0.14.3

Regards

**Comment by neslerel** [comment]
Thanks @hyperprogram2 for reporting it. I'll ckeck it!

**Comment by neslerel** [comment]
Wow! I had problems to find the issue. It was saving the data in the shapefile... The demand value has more digits than allowed and it failed to save the other properties...
It is fixed! Thanks @hyperprogram2

**Comment by hyperprogram2** [comment]
Nice
When will you release the corrected version ?

**Comment by neslerel** [comment]
I would like to fix the issue with the interpolation of elevations before releasing a beta version.

**Comment by neslerel** [comment]
Hi @hyperprogram2,

I fixed the problem with the interpolation of elevations.

In this link you can download an unofficial version (0.14.4) to test it.
http://www.redhisp.webs.upv.es/files/QGISRed/QGISRed_v0.14.4.zip

To use it, you have to:
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.14.0 or 1.0.14.3)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

Please, confirm if all the issues you opened are fixed and if yes, please close them. Thanks!!

**Comment by hyperprogram2** [comment]
Hello,
I tried the 0.14.4 version with the same input data (TEST_export_demands.zip) but I still do not have value in IDPattDem for some Junctions (ex: J146783) or demands (ex:J149817)

Regards

**Comment by neslerel** [comment]
Hi @hyperprogram2,

Are you sure? I tested it again and I can see the IdPattern and the 2 demands of the junctions you mentioned.
Dif you follow all the steps? 
Can you review if you have more than one QGISRed version on Windows Applications and Features?

Maybe you have to restart your computer before install the new version (and after unistall the plugin and the QGISRed program)... I don't know... Only just in case it fix the problem...

I'm going to test it in other computer...

**Comment by hyperprogram2** [comment]
Hi,
I confirm.
I follow the steps.
I restart severals times.
0.14.4 version is installed after uninstalling previous version (several try)

Bugs on timestep results are well resolved by 0.14.4 but issues remain for elevation interpolation (with comma as decimal separator) and Idpattern import

**Comment by hyperprogram2** [comment]
I've found 
I had two Qgisred (0.14.3 and 0.14.4) in Windows app.

After uninstall and intall, it's OK :    Pattern Import  and Interpolation are OK

Thank you

**Comment by neslerel** [comment]
Perfect, I am very happy!
